export default actionTypes = {
  CHECK_LOGIN: 'CHECK_LOGIN',
  SHOW_APP_MESSAGE: 'UPDATE_APP_MESSAGE',
  CLEAR_APP_MESSAGE: 'CLEAR_APP_MESSAGE',
  LOAD_WORKFLOWS: 'LOAD_WORKFLOWS',
  ADD_WORKFLOWS: 'ADD_WORKFLOWS',
  UPDATE_WORKFLOWS: 'UPDATE_WORKFLOWS',
  REMOVE_WORKFLOW: 'REMOVE_WORKFLOW'
}